spring:
  # 設定ファイル読込
  config:
    import:
      - "classpath:/local/crypt.properties"
      - "classpath:/local/jdbc.properties"
      - "classpath:/local/system.properties"
      - "classpath:/local/aws.properties"
      - "classpath:/local/healthInfo.properties"
  messages:
    basename: 
      - messages
      - local/commonErrorCode
      - local/validateErrorCode
      - local/businessErrorCode