server:
  port: 8082
front:
  url: http://localhost:8083
  news:
    page: 10
  note:
    page: 10
  account:
    page: 10
  api:
    page: 10
  healthinfo:
    page: 10
  inquiry:
    page: 10
  job:
    page: 10
spring:
  # 設定ファイル読込
  config:
    import:
      - "classpath:/local/jdbc.properties"
      - "classpath:/local/system.properties"
      - "classpath:/local/aws.properties"
      - "classpath:/local/healthInfo.properties"
