spring:
  application:
    name: ha-api
  security:
    enabled: false
  messages:
    basename: messages
    fallback-to-system-locale: false
    locale: ja
    cache-duration: 1s
  thymeleaf:
    check-template-location: false
  freemarker:
    template-loader-path: classpath:/templates/mail-templates/
    default-encoding: UTF-8
    suffix: .ftl
    charset: UTF-8
    cache: false