server:
  port: 8081
spring:
# 設定ファイル読込
  config:
    import:
      - "classpath:/local/jdbc.properties"
      - "classpath:/local/system.properties"
      - "classpath:/local/aws.properties"
      - "classpath:/local/healthInfo.properties"
